apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  labels:
    role: mongodb-SHARD
  name: mongo-SHARD-persistent-storage-claim-mongodb-SHARD-REPLICA
  namespace: NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: CAPACITY
#  volumeName: k8s-mongodb-NAMESPACE-data-DISK  
  status:
  accessModes:
  - ReadWriteOnce
