apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: k8s-mongodb-lvi123-config-1
spec:
  capacity:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    fsType: ext4
    pdName: pd-ssd-disk-k8s-mongodb-lvi123-5Gi-1

