apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  labels:
    role: mongodb-shard1
  name: mongo-shard1-persistent-storage-claim-mongodb-shard1-0
  namespace: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: data-volume-k8s-mongodb-daemonsl-10g-1
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
