apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  labels:
    role: mongodb-shard2
  name: mongo-shard2-persistent-storage-claim-mongodb-shard2-0
  namespace: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: data-volume-k8s-mongodb-daemonsl-10g-2
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
