apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ilya-mongodb
  name: pvc-data-shard1-replica1
  labels:
    role: shard1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: sc-data
