apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ilya-mongodb
  name: pvc-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: sc-config
